### ISSUE TITLE
Initial TODO

### ISSUE THREAD

**Issue by Pharmhaus-2** [Pharmhaus-2/quicksilver#1]
- [x] Convert to rust workspace
- [x] Update dependencies to current version
- [x] use glow update changes from https://github.com/flukejones/golem
